// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: clientstreaming.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_clientstreaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_clientstreaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_clientstreaming_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Number struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Number) Reset() {
	*x = Number{}
	mi := &file_clientstreaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Number) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Number) ProtoMessage() {}

func (x *Number) ProtoReflect() protoreflect.Message {
	mi := &file_clientstreaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Number.ProtoReflect.Descriptor instead.
func (*Number) Descriptor() ([]byte, []int) {
	return file_clientstreaming_proto_rawDescGZIP(), []int{1}
}

func (x *Number) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_clientstreaming_proto protoreflect.FileDescriptor

const file_clientstreaming_proto_rawDesc = "" +
	"\n" +
	"\x15clientstreaming.proto\"#\n" +
	"\aMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1e\n" +
	"\x06Number\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value26\n" +
	"\x0fClientStreaming\x12#\n" +
	"\n" +
	"MyFunction\x12\b.Message\x1a\a.Number\"\x00(\x01B\bZ\x06.;mainb\x06proto3"

var (
	file_clientstreaming_proto_rawDescOnce sync.Once
	file_clientstreaming_proto_rawDescData []byte
)

func file_clientstreaming_proto_rawDescGZIP() []byte {
	file_clientstreaming_proto_rawDescOnce.Do(func() {
		file_clientstreaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clientstreaming_proto_rawDesc), len(file_clientstreaming_proto_rawDesc)))
	})
	return file_clientstreaming_proto_rawDescData
}

var file_clientstreaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clientstreaming_proto_goTypes = []any{
	(*Message)(nil), // 0: Message
	(*Number)(nil),  // 1: Number
}
var file_clientstreaming_proto_depIdxs = []int32{
	0, // 0: ClientStreaming.MyFunction:input_type -> Message
	1, // 1: ClientStreaming.MyFunction:output_type -> Number
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clientstreaming_proto_init() }
func file_clientstreaming_proto_init() {
	if File_clientstreaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clientstreaming_proto_rawDesc), len(file_clientstreaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clientstreaming_proto_goTypes,
		DependencyIndexes: file_clientstreaming_proto_depIdxs,
		MessageInfos:      file_clientstreaming_proto_msgTypes,
	}.Build()
	File_clientstreaming_proto = out.File
	file_clientstreaming_proto_goTypes = nil
	file_clientstreaming_proto_depIdxs = nil
}
