// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: bidirectional.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_bidirectional_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_bidirectional_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_bidirectional_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_bidirectional_proto protoreflect.FileDescriptor

const file_bidirectional_proto_rawDesc = "" +
	"\n" +
	"\x13bidirectional.proto\"#\n" +
	"\aMessage\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage27\n" +
	"\rBidirectional\x12&\n" +
	"\n" +
	"MyFunction\x12\b.Message\x1a\b.Message\"\x00(\x010\x01B\bZ\x06.;mainb\x06proto3"

var (
	file_bidirectional_proto_rawDescOnce sync.Once
	file_bidirectional_proto_rawDescData []byte
)

func file_bidirectional_proto_rawDescGZIP() []byte {
	file_bidirectional_proto_rawDescOnce.Do(func() {
		file_bidirectional_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bidirectional_proto_rawDesc), len(file_bidirectional_proto_rawDesc)))
	})
	return file_bidirectional_proto_rawDescData
}

var file_bidirectional_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bidirectional_proto_goTypes = []any{
	(*Message)(nil), // 0: Message
}
var file_bidirectional_proto_depIdxs = []int32{
	0, // 0: Bidirectional.MyFunction:input_type -> Message
	0, // 1: Bidirectional.MyFunction:output_type -> Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bidirectional_proto_init() }
func file_bidirectional_proto_init() {
	if File_bidirectional_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bidirectional_proto_rawDesc), len(file_bidirectional_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bidirectional_proto_goTypes,
		DependencyIndexes: file_bidirectional_proto_depIdxs,
		MessageInfos:      file_bidirectional_proto_msgTypes,
	}.Build()
	File_bidirectional_proto = out.File
	file_bidirectional_proto_goTypes = nil
	file_bidirectional_proto_depIdxs = nil
}
